### ISSUE TITLE
App is shifting out of screen when keyboard open

### ISSUE THREAD

**Issue by ShantanuVidwans** [dev-kasibhatla/krissues#10]
The Notification bar should disappear or the app extend till lower edge of Notification bar
![Screenshot_2020-08-13-17-53-19-736_com inator Krushinavakalpana](https://user-images.githubusercontent.com/49361828/90263624-886f0480-de6d-11ea-9f47-934c78f8b26b.jpg)
![Screenshot_2020-08-13-17-56-52-711_com inator Krushinavakalpana](https://user-images.githubusercontent.com/49361828/90263629-8a38c800-de6d-11ea-902c-97cd45232851.jpg)

MIUI 11 6 inch

App shifts up when keyboard is open to enter some text. This doesn't always occur for all the textbox

**Comment by dev-kasibhatla** [comment]
For your first screenshot:
We can't make the notification bar disappear in specific cases. And the screen must shift up for the text box to appear while typing, so there's not a lot we can do about it, cause if the keyboard covers text input, it would be worse.

For your second screenshot:
Same reason, if the textbox is being blocked by keyboard, it shifts up
But I am working on transferring ```change personal information``` form to a different screen since it is crowding the modal sheet.
This would cause problems on smaller phones
